"""Second Revision

Revision ID: 1b6d2284b051
Revises: 0f70c963e85d
Create Date: 2024-08-12 11:08:39.490329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b6d2284b051'
down_revision: Union[str, None] = '0f70c963e85d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drivers_table', schema=None) as batch_op:
        batch_op.alter_column('firstName',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drivers_table', schema=None) as batch_op:
        batch_op.alter_column('firstName',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
